.ds V 1.27
.de Sp
.if n .sp
.if t .sp 0.4
..
.TH OTFTOPL 1 "LCDF Typetools" "Version \*V"
.SH NAME
otftopl \- create TeX PL metrics files from PostScript OpenType fonts
.SH SYNOPSIS
.B otftopl
\%[\fBoptions\fR]
\%[\fIfont\fR [\fIoutput\fR]]
.SH DESCRIPTION
.BR Otftopl
creates TeX PL metrics (and, optionally, a DVIPS-like encoding file) that
correspond, as far as possible, to a PostScript-flavored OpenType font. If
the file
.I output
is not specified the generated PL metrics go to the standard output.
If the file
.I input
is not specified input comes from the standard input.
.LP
OpenType supports extensive substitutions and complex positionings that TeX
can't handle. Many OpenType instructions useful for the Latin script are
supported by TeX, however, including:
.IP * 3
Glyph substitutions, such as replacing 'a' with small caps 
.SM 'A'.
.IP * 3
Pair kerns, such as moving 'AV' closer together.
.IP * 3
Ligatures, such as replacing 'f' and 'i' with an integrated 'fi'
glyph.
.LP
Otftopl reads an OpenType font, turns on font features chosen by the user,
selects the instructions that TeX supports, and generates PL font metrics
and a DVIPS encoding file that, together, implement those instructions.
Feed the PL font metrics to
.BR pltotf (1)
to get TFM font metrics that TeX can read.
.LP

'
.SH OPTIONS
.PD 0
.TP 5
.BI \-a "\fR, " \-\-pfa
Output font in ASCII PFA format.
'
.Sp
.TP 5
.BI \-b "\fR, " \-\-pfb
Output font in binary PFB format. This is the default.
'
.Sp
.TP 5
.BI \-n " name"
.TP 5
.BI \-\-name " name"
Output the CFF's component font named
.IR name .
CFF files can contain more than one font, although few do. Use this option
to select a particular font from a multi-font collection. By default
cfftot1 chooses the collection's first font.
'
.Sp
.TP 5
.BI \-o " file"
.TP 5
.BI \-\-output " file"
Write output font to
.IR file
instead of the standard output.
'
.Sp
.TP 5
.BR \-q ", " \-\-quiet
Do not generate any error messages.
'
.Sp
.TP 5
.BR \-h ", " \-\-help
Print usage information and exit.
'
.Sp
.TP 5
.BR \-\-version
Print the version number and some short non-warranty information and exit.
.PD
'
.SH "BUGS"
.LP
Otftopl should warn when TeX cannot implement a requested feature (complex
context-sensitive positionings, for example).
.LP
Presumably some context-sensitive positionings and ligatures could be
implemented with TeX's boundary character, but otftopl doesn't do that yet.
.LP
More positionings and ligatures could be supported with the help of virtual
fonts.
'
.SH "SEE ALSO"
.LP
.BR pltotf (1),
.BR tftopl (1),
.BR vptovf (1),
.BR afm2tfm (1),
.BR cfftot1 (1)
.LP
.I "Adobe Type 1 Font Format"
.LP
Adobe Technical Notes #5176,
.IR "The Compact Font Format Specification" ,
and #5177,
.I "The Type 2 Charstring Format"
.LP
.I "OpenType Specification" ,
Version 1.4
'
.SH AUTHOR
Eddie Kohler (kohler@icir.org)
